name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - main  # Runs when you push to main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Updated to latest version

      - name: Create output directory
        run: mkdir -p dist  # Ensures the "dist" folder exists before generating snake.svg

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@master  # Uses latest version
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg
          palette: github-dark

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
